server:
  port: 9091

spring:
  datasource:
    #数据库配置
    url: jdbc:mysql://127.0.0.1:3306/road-map?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  # xml文件位置
  mapper-locations: classpath:/mybatis/mapper/*.xml
  # 实体类别名包扫描
  type-aliases-package: com.codingshen.demo.infrastructure.dal.po
  # 配置文件位置
  config_location: classpath:/mybatis/config/mybatis-config.xml

logging:
  level:
    root: info
  config: classpath:logback-spring.xml

# apollo 配置中心
apollo:
  cacheDir: /opt/data/
  cluster: default
  meta: http://127.0.0.1:8080
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: false
    namespaces: application
    eagerLoad:
      enabled: false